//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QuanLyChungCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public int Id { get; set; }
        public string floor { get; set; }
        public string Square { get; set; }
        public Nullable<int> LeadId { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ApartmentNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
