//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QuanLyChungCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string PayCash { get; set; }
        public string PaymentMethod { get; set; }
        public string StaffId { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> LeadId { get; set; }
        public Nullable<int> ApartmentId { get; set; }
    }
}
