//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QuanLyChungCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string LeadIdentify { get; set; }
        public string Phone { get; set; }
        public string Nationality { get; set; }
        public string BankBranch { get; set; }
        public Nullable<int> StaffId { get; set; }
    }
}
